Feat/select ticket mode
Deltinha/driven.t pull request #5
Opened 2022-01-22 03:04 UTC by samuelfcf

2022-01-22 17:29 UTC, lfelipelizeu approved these changes
Acho que depois a gente pode ver de buscar os tipos de ingresso no banco, ao invés de deixar mockado, já que a gente tem um tabela só pros tipos.

2022-01-22 22:39 UTC, Deltinha approved these changes

2022-01-22 22:39 UTC, Deltinha commented on src/components/PersonalInformationForm/index.js
> +          localStorage.setItem("enrollmentId", enrollmentId);
Eu não acho interessante guardar essa informação no front. Mas como eu vi que já estamos usando ela em vários lugares, tudo bem deixar por enquanto.

No backend, a rota de salvar o pagamento é autenticada. O middleware de autenticação passa o id do usuário através de `req.user.id`. Então bastaria fazer algo do tipo no controller de tickets:
`const enrollmentInfo = await enrollmentService.getEnrollmentWithAddress(req.user.id);`
`const enrollmentId = enrollmentInfo.id;`

2022-01-23 00:49 UTC, samuelfcf commented on src/components/PersonalInformationForm/index.js
> +          localStorage.setItem("enrollmentId", enrollmentId);
Boa! Fiz as alterações, ficou bem mais simples no código :)

2022-01-23 01:15 UTC, lfelipelizeu requested changes

2022-01-23 01:15 UTC, lfelipelizeu commented on src/pages/Dashboard/Payment/index.js
> +        (ticketData.ticketValue === 100
Aqui tem que depender do tipo de ingresso, tipo `ticketData.ticketType === "Online"`, porque daí não depende do preço, desse jeito se mudar o valor do ingresso online para de funcionar.

2022-01-23 01:49 UTC, Deltinha commented
Eu tenho apenas um ticketType na database, Presencial de ID 1. Ao tentar fazer a reserva pelo front, o back devia receber ticketTypeId = 1, mas tá recebendo o valor 2.
{
  value: '100',
  isPaid: false,
  enrollmentId: 8,
  ticketTypeId: 2,
  hasHotel: false
}

2022-01-23 02:38 UTC, lfelipelizeu approved these changes

2022-01-23 17:40 UTC, merged